/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2018-03-27 10:24:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class attr_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+request.getContextPath()+"/";
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<base href=\"");
      out.print(basePath );
      out.write("\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<title>硅谷商城</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"easyui-layout\" data-options=\"fit:true\">\r\n");
      out.write("\t\t<div data-options=\"region:'north',split:true\" style=\"height:50px\">\r\n");
      out.write("\t\t\t\t<div style=\"margin-top:10px;margin-left:10px\">\r\n");
      out.write("\t\t\t\t\t一级：<select data-options=\"width:200\" class=\"easyui-combobox\" id=\"attr_class_1_select\" onchange=\"get_attr_class_2(this.value);\"><option>请选择</option></select>\r\n");
      out.write("\t\t\t\t\t二级：<select data-options=\"width:200\" class=\"easyui-combobox\"  id=\"attr_class_2_select\" onchange=\"get_attr_list_json(this.value)\"><option>请选择</option></select>\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div data-options=\"region:'west',split:true\" style=\"width:100px\">\r\n");
      out.write("\t\t<a href=\"javascript:goto_attr_add()\">添加</a><br>\r\n");
      out.write("\t\t\t查询<br>\r\n");
      out.write("\t\t\t删除<br>\r\n");
      out.write("\t\t\t编辑<br>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div data-options=\"region:'center'\">\r\n");
      out.write("\t\t\t<div id=\"attrListInner\" class=\"easyui-datagrid\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t$(function (){\r\n");
      out.write("/* \t\t$.getJSON(\"js/json/class_1.js\",function(data){\r\n");
      out.write("\t\t\t$(data).each(function(i,json){\r\n");
      out.write("\t\t\t\t$(\"#attr_class_1_select\").append(\"<option value=\"+json.id+\">\"+json.flmch1+\"</option>\");\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}); */\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#attr_class_1_select').combobox({    \r\n");
      out.write("\t\t    url:'js/json/class_1.js',    \r\n");
      out.write("\t\t    valueField:'id',    \r\n");
      out.write("\t\t    textField:'flmch1',\r\n");
      out.write("\t\t    width:200,\r\n");
      out.write("\t\t    onChange:function get_attr_class_2(){\r\n");
      out.write("\t\t    \t// 获取当前的下拉列表被选中的id\r\n");
      out.write("\t\t    \tvar class_1_id = $(this).combobox(\"getValue\");\r\n");
      out.write("\t\t\t\t$('#attr_class_2_select').combobox({    \r\n");
      out.write("\t\t\t\t    url:\"js/json/class_2_\"+class_1_id+\".js\",    \r\n");
      out.write("\t\t\t\t    valueField:'id',    \r\n");
      out.write("\t\t\t\t    textField:'flmch2',\r\n");
      out.write("\t\t\t\t    onChange:function (){\r\n");
      out.write("\t\t\t\t    \tvar flbh2 = $(this).combobox(\"getValue\");\r\n");
      out.write("\t\t\t\t    \tget_attr_list_json(flbh2);\r\n");
      out.write("\t\t\t\t    },\r\n");
      out.write("\t\t\t\t    width:200\r\n");
      out.write("\t\t\t\t });\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});  \r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction get_attr_class_2(class_1_id){\r\n");
      out.write("\t\t$.getJSON(\"js/json/class_2_\"+class_1_id+\".js\",function(data){\r\n");
      out.write("\t\t\t$(\"#attr_class_2_select\").empty();\r\n");
      out.write("\t\t\t$(data).each(function(i,json){\r\n");
      out.write("\t\t\t\t$(\"#attr_class_2_select\").append(\"<option value=\"+json.id+\">\"+json.flmch2+\"</option>\");\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction goto_attr_add(){\r\n");
      out.write("\t\tvar class_2_id = $(\"#attr_class_2_select\").combobox(\"getValue\");//$(\"#attr_class_2_select\").val();\t\t\r\n");
      out.write("\t\t//window.location.href=\"goto_attr_add.do?flbh2=\"+class_2_id;\r\n");
      out.write("\t\tadd_tab(\"goto_attr_add.do?flbh2=\"+class_2_id,\"添加属性\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction get_attr_list(flbh2){\r\n");
      out.write("\t\t// 异步查询\r\n");
      out.write(" \t\t$.post(\"get_attr_list.do\",{flbh2:flbh2},function(data){\r\n");
      out.write("\t\t\t$(\"#attrListInner\").html(data);\r\n");
      out.write("\t\t}); \r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction get_attr_list_json(flbh2){\r\n");
      out.write("\t\t// 异步查询\r\n");
      out.write("\t\t$('#attrListInner').datagrid({    \r\n");
      out.write("\t\t    url:'get_attr_list_json.do',   \r\n");
      out.write("\t\t    queryParams: {\r\n");
      out.write("\t\t    \tflbh2: flbh2\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t    columns:[[    \r\n");
      out.write("\t\t        {field:'id',title:'id',width:100},    \r\n");
      out.write("\t\t        {field:'shxm_mch',title:'属性名',width:100},    \r\n");
      out.write("\t\t        {field:'list_value',title:'属性值',width:300,\r\n");
      out.write("\t\t        \tformatter: function(value,row,index){\r\n");
      out.write("\t\t        \t\tvar str = \"\";\r\n");
      out.write("\t\t\t\t\t\t// 处理字段值的代码\r\n");
      out.write("\t\t\t\t\t\t$(value).each(function(i,json){\r\n");
      out.write("\t\t\t\t\t\t\tstr = str + json.shxzh+json.shxzh_mch + \" \";\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\treturn str;\r\n");
      out.write("\t\t\t\t\t}\t\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t        {field:'chjshj',title:'创建时间',width:300,\r\n");
      out.write("\t\t        \tformatter: function(value,row,index){\r\n");
      out.write("\t\t        \t\tvar d = new Date(value);\r\n");
      out.write("\t\t        \t\tvar str = d.toLocaleString();\r\n");
      out.write("\t\t\t\t\t\treturn str;\r\n");
      out.write("\t\t\t\t\t}\t\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t    ]]    \r\n");
      out.write("\t\t});  \r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
