/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2018-03-27 10:24:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+request.getContextPath()+"/";
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<base href=\"");
      out.print(basePath );
      out.write("\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"js/easyui/themes/default/easyui.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"js/easyui/themes/icon.css\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/easyui/jquery.easyui.min.js\"></script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t\tvar title = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t\tif(url!=\"\"&&title!=\"\"){\t\r\n");
      out.write("\t\t\tadd_tab(url,title);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction add_tab(url,title){\r\n");
      out.write("\t\t// add a new tab panel  \r\n");
      out.write("\t\tvar b = $('#tt').tabs('exists',title);\r\n");
      out.write("\t\tif(!b){\r\n");
      out.write("\t\t\t$('#tt').tabs('add',{    \r\n");
      out.write("\t\t\t    title:title,    \r\n");
      out.write("\t\t\t    href:url,    \r\n");
      out.write("\t\t\t    closable:true,    \r\n");
      out.write("\t\t\t    tools:[{    \r\n");
      out.write("\t\t\t        iconCls:'icon-mini-refresh',    \r\n");
      out.write("\t\t\t        handler:function(){    \r\n");
      out.write("\t\t\t            alert('refresh');    \r\n");
      out.write("\t\t\t        }    \r\n");
      out.write("\t\t\t    }]    \r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$('#tt').tabs('select',title);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction add_tab2(url,title){\r\n");
      out.write("\t\t// add a new tab panel    \r\n");
      out.write("\t\t$.post(url,function(data){\r\n");
      out.write("\t\t\t$('#tt').tabs('add',{    \r\n");
      out.write("\t\t\t    title:title,    \r\n");
      out.write("\t\t\t    content:data,    \r\n");
      out.write("\t\t\t    closable:true,    \r\n");
      out.write("\t\t\t    tools:[{    \r\n");
      out.write("\t\t\t        iconCls:'icon-mini-refresh',    \r\n");
      out.write("\t\t\t        handler:function(){    \r\n");
      out.write("\t\t\t            alert('refresh');    \r\n");
      out.write("\t\t\t        }    \r\n");
      out.write("\t\t\t    }]    \r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<title>硅谷商城</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"easyui-layout\">\r\n");
      out.write("\t<div data-options=\"region:'north',border:false\" style=\"height:60px;background:#B3DFDA;padding:10px\">north region</div>\r\n");
      out.write("\t<div data-options=\"region:'west',split:true,title:'West'\" style=\"width:180px;padding:10px;\">\r\n");
      out.write("\t\t<div class=\"easyui-accordion\" style=\"width:160px;\">\r\n");
      out.write("\t\t\t<div title=\"About\" data-options=\"iconCls:'icon-ok'\" >\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"javascript:add_tab('goto_spu.do','商品信息管理')\">商品信息管理</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"javascript:add_tab('goto_attr.do','商品属性管理')\" >商品属性管理</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"javascript:add_tab('goto_sku.do','商品库存单元管理')\" >商品库存单元管理</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div title=\"About\" data-options=\"iconCls:'icon-ok'\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>商品缓存管理</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div data-options=\"region:'east',split:true,collapsed:true,title:'East'\" style=\"width:100px;padding:10px;\">east region</div>\r\n");
      out.write("\t<div data-options=\"region:'south',border:false\" style=\"height:50px;background:#A9FACD;padding:10px;\">south region</div>\r\n");
      out.write("\t<div data-options=\"region:'center',title:'Center'\">\r\n");
      out.write("\t\t<div id=\"tt\" class=\"easyui-tabs\" style=\"height:500px\">\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
