/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2018-03-27 05:51:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class spu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+request.getContextPath()+"/";
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<base href=\"");
      out.print(basePath );
      out.write("\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<title>硅谷商城</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\tspu商品信息管理\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t一级：<select id=\"class_1_select\" onchange=\"get_class_2(this.value);\"><option>请选择</option></select>\r\n");
      out.write("\t二级：<select  id=\"class_2_select\"><option>请选择</option></select>\r\n");
      out.write("\t品牌：<select  id=\"tm_select\"><option>请选择</option></select><br>\r\n");
      out.write("\t查询<br>\r\n");
      out.write("\t<a href=\"javascript:goto_spu_add();\">添加</a><br>\r\n");
      out.write("\t删除<br>\r\n");
      out.write("\t编辑<br>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function (){\r\n");
      out.write("\t\t$.getJSON(\"js/json/class_1.js\",function(data){\r\n");
      out.write("\t\t\t$(data).each(function(i,json){\r\n");
      out.write("\t\t\t\t$(\"#class_1_select\").append(\"<option value=\"+json.id+\">\"+json.flmch1+\"</option>\");\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction get_class_2(class_1_id){\r\n");
      out.write("\t\t$.getJSON(\"js/json/class_2_\"+class_1_id+\".js\",function(data){\r\n");
      out.write("\t\t\t$(\"#class_2_select\").empty();\r\n");
      out.write("\t\t\t$(data).each(function(i,json){\r\n");
      out.write("\t\t\t\t$(\"#class_2_select\").append(\"<option value=\"+json.id+\">\"+json.flmch2+\"</option>\");\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tget_tm(class_1_id);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction get_tm(class_1_id){\r\n");
      out.write("\t\t$.getJSON(\"js/json/tm_class_1_\"+class_1_id+\".js\",function(data){\r\n");
      out.write("\t\t\t$(\"#tm_select\").empty();\r\n");
      out.write("\t\t\t$(data).each(function(i,json){\r\n");
      out.write("\t\t\t\t$(\"#tm_select\").append(\"<option value=\"+json.id+\">\"+json.ppmch+\"</option>\");\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction goto_spu_add(){\r\n");
      out.write("\t\tvar class_1_id = $(\"#class_1_select\").val();\r\n");
      out.write("\t\tvar class_2_id = $(\"#class_2_select\").val();\r\n");
      out.write("\t\tvar tm_id = $(\"#tm_select\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\twindow.location.href=\"goto_spu_add.do?flbh1=\"+class_1_id+\"&flbh2=\"+class_2_id+\"&pp_id=\"+tm_id;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
