/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2018-04-03 08:28:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+request.getContextPath()+"/";
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<base href=\"");
      out.print(basePath );
      out.write("\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/icon\" href=\"images/jd.ico\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/login.css\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction to_submit(){\r\n");
      out.write("\t\t$(\"#login_form\").submit();\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<title>硅谷商城</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\t\t<div class=\"up\">\r\n");
      out.write("\t\t\t<img src=\"images/logo.jpg\" height=\"45px;\" class=\"hy_img\"/>\r\n");
      out.write("\t\t\t<div class=\"hy\">\r\n");
      out.write("\t\t\t\t欢迎登录\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"middle\">\r\n");
      out.write("\t\t\t<div class=\"login\">\r\n");
      out.write("\t\t\t\t<div class=\"l1 \">\r\n");
      out.write("\t\t\t\t\t<div class=\"l1_font_01 \">硅谷会员</div>\r\n");
      out.write("\t\t\t\t\t<a class=\"l1_font_02 \" href=\"");
      out.print(application.getContextPath() );
      out.write("/to_regist.action\">用户注册</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"blank_01\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"ts\">\r\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${err}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"blank_01\"></div>\r\n");
      out.write("\t\t\t\t<form action=\"login.do\" id=\"login_form\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<div class=\"input1\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"input1_01\" name=\"yh_mch\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"blank_01\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"blank_01\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"input2\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"input1_01\" name=\"yh_mm\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"blank_01\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"blank_01\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"box_01\">\r\n");
      out.write("\t\t\t\t\t<div class=\"box_01_both\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"box_01_both_1\">数据源1：<input type=\"radio\" name=\"dataSource_type\" value=\"1\"/></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"box_01_both_2\">数据源2：<input type=\"radio\" name=\"dataSource_type\" value=\"2\"/></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<div class=\"blank_01\"></div>\r\n");
      out.write("\t\t\t\t<a href=\"javascript:;\" class=\"aline\">\r\n");
      out.write("\t\t\t\t\t<div class=\"red_button\" onclick=\"to_submit()\">\r\n");
      out.write("\t\t\t\t\t\t登&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;录\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div class=\"blank_01\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"blank_01\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"box_down\">\r\n");
      out.write("\t\t\t\t\t<div class=\"box_down_1\">使用合作网站账号登录京东：</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"box_down_1\">京东钱包&nbsp;&nbsp;|&nbsp;&nbsp;QQ \r\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;|&nbsp;&nbsp;微信\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"down\">\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\tCopyright©2004-2015  xu.jb.com 版权所有\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
